site_name: 鲤鱼的小站
theme:
  name: material #主题设置
  #custom_dir: overrides # 主题扩展(覆写)文件夹
  icon:
    logo: material/library #TODO:自己换一个logo，现在使用的是默认的样例logo
    #favicon: images/favicon.png #TODO:网页标签栏显示的图标，后续进行更换即可
  language: zh #设置语言为简体中文
  palette:
    # 浅色模式
    - #根据用户系统设置自动切换模式
      media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        #图标，这里直接使用内嵌的图标库，也可以使用内联svg(?)或自定义图标
        icon: material/toggle-switch-off-outline
        name: 切换到夜间模式

    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换到日间模式
  features:
    - navifation.instant # 即时加载
    - navifation.instant.progress # 页面加载进度条
    - navifation.tracking # 锚点跟踪
    #- navigation.tabs # 宽度适合时在上方显示导航栏
    #- navigation.tabs.sticky # 导航栏常驻
    - navigation.sections # 左侧导航标签分组
    #- navigation.expand # 左侧导航栏自动展开
    #- navigation.path # Insiders Only, 在上方显示当前导航所在目录
    - navigation.prune # 导航精简，减少构建网页时的消耗
    #- navigation.indexes # (?)
    - toc.follow # (?)
    - toc.integrate # 两侧的toc集成到左侧
    - navigation.top # 返回顶部按钮，仅在上划时出现
    - search.suggest # 搜索建议候选
    #- search.highlight # 搜索到的结果在打开的页面内高亮
    - search.share # (?)
    - header.autohide # header滚动时自动隐藏
    #- announce.dismiss # 通知可标记为已读并关闭
    - navigation.footer # 页脚增添上页下页功能
plugins:
  #- privacy #内置隐私插件(?)
  - search #内置搜索插件
  - blog # TODO:博客插件
    #写法规范：https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
  - tags: # Hash Tags
      tags_file: tags.md # 设置标签页
extra:
  #alternate:
  #TODO:语言切换功能
  #参考https://squidfunk.github.io/mkdocs-material/setup/changing-the-language
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/383910359
      name: Bilibili
    - icon: fontawesome/brands/github
      link: https://github.com/lixingjian-C
      name: Github
    #- X/Twitter
    #- Patron
extra_css:
  - stylesheets/transition-light-dark.css #浅色、深色模式切换过渡效果
copyright: | # 版权声明
  Copyright &copy; 2024 - 2024 Owen Li. All Rights Reserved.<br>
  Code licensed under the <a href="https://opensource.org/license/MIT target="_blank" rel="noopener">MIT</a> License. Content licensed under <a href="https://creativecommons.org/licenses/by/4.0/deed.zh-hans" target="_blank" rel="noopener">CC BY 4.0</a>.
